// Mocks generated by Mockito 5.4.6 from annotations
// in first_demo/test/pages/animal_image/repository_animal_image_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:first_demo/features/animal_image/api_animal_image.dart' as _i2;
import 'package:first_demo/features/animal_image/model_animal_image.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AnimalApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnimalApi extends _i1.Mock implements _i2.AnimalApi {
  @override
  _i3.Future<List<_i4.Animal>> getAnimals(
    String? animal, {
    int? limit = 20,
    int? page = 1,
    String? order = 'desc',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAnimals,
          [animal],
          {
            #limit: limit,
            #page: page,
            #order: order,
          },
        ),
        returnValue: _i3.Future<List<_i4.Animal>>.value(<_i4.Animal>[]),
        returnValueForMissingStub: _i3.Future<List<_i4.Animal>>.value(<_i4.Animal>[]),
      ) as _i3.Future<List<_i4.Animal>>);
}
