// Mocks generated by Mockito 5.4.6 from annotations
// in first_demo/test/features/moments/user/repository_user_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:first_demo/features/moments/api_moments.dart' as _i3;
import 'package:first_demo/features/moments/tweet/index.dart' as _i5;
import 'package:first_demo/features/moments/user/index.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MomentsApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockMomentsApi extends _i1.Mock implements _i3.MomentsApi {
  @override
  _i4.Future<_i2.User> getUser() => (super.noSuchMethod(
        Invocation.method(
          #getUser,
          [],
        ),
        returnValue: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.User>.value(_FakeUser_0(
          this,
          Invocation.method(
            #getUser,
            [],
          ),
        )),
      ) as _i4.Future<_i2.User>);

  @override
  _i4.Future<List<_i5.Tweet>> getTweets() => (super.noSuchMethod(
        Invocation.method(
          #getTweets,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Tweet>>.value(<_i5.Tweet>[]),
        returnValueForMissingStub: _i4.Future<List<_i5.Tweet>>.value(<_i5.Tweet>[]),
      ) as _i4.Future<List<_i5.Tweet>>);
}
